export interface IProduct {
  id: number,
  imageURL: string,
  name: string,
  price: number,
  soldOut: boolean,
  description: string
}

export const products : IProduct[] = [
  {
    id: 1,
    imageURL: "https://placekitten.com/320/200",
    name: "Monitor 4K",
    price: 0.00,
    soldOut: true,
    description: "À vista no PIX",
  },
  {
    id: 2,
    imageURL: "https://placekitten.com/320/200",
    name: "Monitor 4K",
    price: 0.00,
    soldOut: true,
    description: "À vista no PIX",
  },
  {
    id: 3,
    imageURL: "https://placekitten.com/320/200",
    name: "Monitor 4K",
    price: 0.00,
    soldOut: true,
    description: "À vista no PIX",
  },
  {
    id: 4,
    imageURL: "https://placekitten.com/320/200",
    name: "Monitor 4K",
    price: 0.00,
    soldOut: true,
    description: "À vista no PIX",
  },
  {
    id: 5,
    imageURL: "https://placekitten.com/320/200",
    name: "Monitor 4K",
    price: 0.00,
    soldOut: true,
    description: "À vista no PIX",
  },
  {
    id: 6,
    imageURL: "https://placekitten.com/320/200",
    name: "Monitor 4K",
    price: 0.00,
    soldOut: true,
    description: "À vista no PIX",
  },
  {
    id: 7,
    imageURL: "https://placekitten.com/320/200",
    name: "Monitor 4K",
    price: 0.00,
    soldOut: true,
    description: "À vista no PIX",
  },
  {
    id: 8,
    imageURL: "https://placekitten.com/320/200",
    name: "Monitor 4K",
    price: 0.00,
    soldOut: true,
    description: "À vista no PIX",
  },
  {
    id: 9,
    imageURL: "https://placekitten.com/320/200",
    name: "Monitor 4K",
    price: 0.00,
    soldOut: true,
    description: "À vista no PIX",
  },
  {
    id: 10,
    imageURL: "https://placekitten.com/320/200",
    name: "Monitor 4K",
    price: 0.00,
    soldOut: true,
    description: "À vista no PIX",
  },
  {
    id: 11,
    imageURL: "https://placekitten.com/320/200",
    name: "Monitor 4K",
    price: 0.00,
    soldOut: true,
    description: "À vista no PIX",
  },
  {
    id: 12,
    imageURL: "https://placekitten.com/320/200",
    name: "Monitor 4K",
    price: 0.00,
    soldOut: true,
    description: "À vista no PIX",
  },
  {
    id: 13,
    imageURL: "https://placekitten.com/320/200",
    name: "Monitor 4K",
    price: 0.00,
    soldOut: true,
    description: "À vista no PIX",
  },
  {
    id: 14,
    imageURL: "https://placekitten.com/320/200",
    name: "Monitor 4K",
    price: 0.00,
    soldOut: true,
    description: "À vista no PIX",
  },
  {
    id: 15,
    imageURL: "https://placekitten.com/320/200",
    name: "Monitor 4K",
    price: 0.00,
    soldOut: true,
    description: "À vista no PIX",
  },
  {
    id: 16,
    imageURL: "https://placekitten.com/320/200",
    name: "Monitor 4K",
    price: 0.00,
    soldOut: true,
    description: "À vista no PIX",
  },
  {
    id: 17,
    imageURL: "https://placekitten.com/320/200",
    name: "Monitor 4K",
    price: 0.00,
    soldOut: true,
    description: "À vista no PIX",
  },
  {
    id: 18,
    imageURL: "https://placekitten.com/320/200",
    name: "Monitor 4K",
    price: 0.00,
    soldOut: true,
    description: "À vista no PIX",
  },
  {
    id: 19,
    imageURL: "https://placekitten.com/320/200",
    name: "Monitor 4K",
    price: 0.00,
    soldOut: true,
    description: "À vista no PIX",
  },
  {
    id: 20,
    imageURL: "https://placekitten.com/320/200",
    name: "Monitor 4K",
    price: 0.00,
    soldOut: true,
    description: "À vista no PIX",
  },
  {
    id: 21,
    imageURL: "https://placekitten.com/320/200",
    name: "Monitor 4K",
    price: 0.00,
    soldOut: true,
    description: "À vista no PIX",
  }
]